version: '3.8'

services:
  app:
    build:
      context: .  # Use the current directory
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_PATH=${HOST_BASE_PATH:-}
    ports:
      - "${HOST_PORT:-8081}:3000"  # External port maps to internal port 3000 (as exposed in Dockerfile)
    environment:
      - NODE_ENV=production  # Set the environment variable to production
    volumes:
      - ./data:/app/data  # Mount the volume for your SQLite database
